import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Observable, of } from 'rxjs';
import { ForumDto, CategoryClient, ForumClient } from 'src/app/generated/forum-api.service';
import { map } from 'rxjs/operators';

// TODO: this is temporary. Will be replaced with models generated by nswag
export interface ForumListingItem {
  id: number;
  title: string;
  body: string;
  timeCreated: Date;
}

@Component({
  selector: 'app-forums-listing',
  templateUrl: './forums-listing.component.html',
  styleUrls: ['./forums-listing.component.scss']
})
export class ForumsListingComponent implements OnInit {

  constructor(
    private _categoryService: CategoryClient,
    private _forumService: ForumClient,
    private _router: Router) { }

  public forums$: Observable<ForumDto[]>;

  public ngOnInit(): void {
    this.forums$ = this._forumService.all(null, null);
  }

  public goToForum(forum: ForumListingItem): void {
    this._router.navigate(['/forums', forum.id]);
  }

}
